version: '3'

services:
  db:
    image: postgres:13.1
    volumes: 
      - "$PWD/db/onDBOpen:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  middletier:
    image: maven:3.8.6-jdk-11
    command: /bin/bash -c "cd ./middletier && mvn clean && mvn install && mvn -pl=./web tomee:run"
    volumes:
      - "$PWD/middletier:/middletier"
    depends_on:
      - db
  frontend:
    image: node:16
    command: bash -c "cd /frontend && yarn && yarn start"
    volumes: 
      - "$PWD/frontend:/frontend"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true